AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  DomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "domain name of the website"
    Default: /DomainName
  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "R53 hosted zone ID used for the domain"
    Default: /HostedZoneId
  CertificateARN:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "arn for SSL Certificate"
    Default: /CertificateARN

Resources:
  ResumeFunction:
    Type: AWS::Serverless::Function # 
    Properties:
      CodeUri: resume_lambda/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      Policies: 
        - AmazonDynamoDBFullAccess
      Events:
        ResumeAPI:
          Type: Api #
          Properties:
            Path: /visitorCount
            Method: get
  
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: www.clouddanny.net

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref ResumeBucket
                - /*
      Bucket: !Ref ResumeBucket

  # ACMCert:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: !Ref DomainName
  #     ValidationMethod: DNS

  CloudFrontDistro:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: sni-only
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: www.clouddanny.net.s3-website-us-east-1.amazonaws.com
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
             QueryString: false
        Origins:
          - DomainName: www.clouddanny.net.s3-website-us-east-1.amazonaws.com
            Id: www.clouddanny.net.s3-website-us-east-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html

  Route53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:  !Ref HostedZoneId #
      RecordSets:
        - Name: !Ref DomainName #
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudFrontDistro.DomainName

  ResumeDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitorCountTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "visitsCount"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "visitsCount"
          KeyType: "HASH"


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ResumeAPI:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitorCount/"
  ResumeFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ResumeFunction.Arn
  ResumeFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ResumeFunctionRole.Arn
