name: main
on: [push]


jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: installing python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage flake8 moto boto3
      - name: test lambda-functionalities
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: cd tests/unit && pytest -k test -v ./ && cd ../../
      

      


